### ISSUE TITLE
Changing http libraries?

### ISSUE THREAD

**Issue by scratchyone** [halcyonnouveau/roux.rs#10]
Roux is currently using an out of date version of reqwest. The latest version doesn't appear to support synchronous requests. Should this project change to a different library, so that it can use the latest version? I quite like ureq, it's simple, sync, and seems to be actively maintained. I'm worried that reqwest is permanently blocking if the server doesn't respond correctly, since sometimes my bot just completely freezes with no error. It doesn't seem to be the pushshift library I wrote, because that uses ureq and returns Err if it takes more than 10 seconds to receive a response.

**Comment by scratchyone** [comment]
I'm running a test currently with extra logging, so I should be able to figure out if it's reqwest that's causing the issue pretty soon.

**Comment by scratchyone** [comment]
ok so the issue is not the library blocking. Currently, it's still able to successfully retrieve from pushshift but has stopped being able to edit the posts and has stopped being able to respond to PMs. It's not throwing any errors which is strange

**Comment by beanpuppy** [comment]
Yeah I've been meaning to update reqwest for a while, I just haven't found any features or bugs to make it urgent. But just as an FYI, reqwest does have an optional [blocking client](https://github.com/seanmonstar/reqwest#blocking-client), otherwise you could just use `async` and `await` everywhere.

I've never used ureq before and it does look interesting. We definitely don't need all the features of reqwest so a smaller and simpler library would be welcome. But that all depends on how much work is involved.

Can't really say much about your bot without seeing it, but is the issue any similar to [this](https://github.com/seanmonstar/reqwest/issues/746)?

**Comment by scratchyone** [comment]
If you want, I could try to work on a PR changing to ureq. Also what’s
super strange is that my entire bot is in a loop {} with thread::sleep, and
it continues to loop (tested with print statements) but stops answering PMs
and stops editing its status post. I’ve updated it to add even more logging
and a bunch of unwraps to try to get an error message, but it hasn’t had
the issue since then. It’s possible that Reddit’s api was having some
issues
--

**Comment by beanpuppy** [comment]
You can certainly create a PR if you want. I'm still not completely convinced that it's worth the time, but if you're able to manage it without any problems or disruptions to existing workflows then that'd be great.

**Comment by beanpuppy** [comment]
Closing, reqwest updated for async/await in c9fb525c8e8b5485aaad4422a88ec370e4ce9c9b.
